// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aanollewetntdojenubs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhbm9sbGV3ZXRudGRvamVudWJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE1MzU3ODIsImV4cCI6MjA5NzExMTc4Mn0.g6_mStqVHkgF-Ots9DbA5PTgHTikT9qm2BeRUabrvng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});