// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmygggcwwrxrsbqnghpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJteWdnZ2N3d3J4cnNicW5naHB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk4MzY0NTcsImV4cCI6MjA5NTQxMjQ1N30.7rLBQjujLybeDr95ql4fNjb6uTcfsiFZI35uT5zsGjc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});