// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpbcgkrizrpwfjrpynig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwYmNna3JpenJwd2ZqcnB5bmlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0NjU4MDEsImV4cCI6MjA5MTA0MTgwMX0.Lu8M9Ge7Ms8ZpyvS4dfBKeXIg7I8CY3aPeDvNwyDtGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});